# Generated by Django 3.1 on 2020-08-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_fridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
    ]
