# Generated by Django 3.1 on 2020-08-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_fridge', '0002_auto_20200810_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'food'},
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('kilogram', 'Kg'), ('gram', 'g'), ('litre', 'L'), ('unit', 'unit')], max_length=15)),
                ('quant', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_fridge.food')),
            ],
            options={
                'verbose_name_plural': 'quantities',
            },
        ),
    ]
