# Generated by Django 3.1 on 2020-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_fridge', '0003_auto_20200810_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'Food'},
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
