# Generated by Django 3.1 on 2020-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_fridge', '0004_auto_20200810_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='units',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('unit', 'Unit')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
