# Generated by Django 3.1 on 2020-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_fridge', '0005_auto_20200810_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('units', models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('unit', 'Unit')], max_length=15)),
                ('quantity', models.FloatField(default=0.0)),
            ],
        ),
    ]
